---

version: "3"

services:
  app:
    command: 'nodos server -h 0.0.0.0'
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    volumes:
      - .:/app
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
