---

version: "3"

services:
  app:
    build: .
    command: 'npm test'
    # command: 'nodos server -h 0.0.0.0'
    # volumes:
    #   - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '${NODOS_DB_USERNAME}'
      POSTGRES_USER: '${NODOS_DB_PASSWORD}'
